### ISSUE TITLE
Support --experimental_allow_proto3_optional option

### ISSUE THREAD

**Issue by 2is10** [ksprojects/protobuf-jetbrains-plugin#153]
**Is your feature request related to a problem? Please describe.**

Since protoc version 3.12.0, `--experimental_allow_proto3_optional` enables the use of `optional` in proto3 for explicit field presence.

https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

When I try to use `--experimental_allow_proto3_optional`, it’s unrecognized in IntelliJ, and the `optional` keyword is still forbidden.

**Describe the solution you'd like**

See screenshots. Ideally there would be no errors.

**Additional context**

![image](https://user-images.githubusercontent.com/647851/85635384-95703400-b632-11ea-8540-7f9bb9daa971.png)

![image](https://user-images.githubusercontent.com/647851/85635393-9a34e800-b632-11ea-9c0f-cd1f309bd7cb.png)

**Comment by jvolkman** [comment]
This plugin isn't supported anymore. Maybe add a note to https://github.com/jvolkman/intellij-protobuf-editor/issues/7?

**Comment by kshchepanovskyi** [comment]
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.
