### ISSUE TITLE
Ability to turn off code formatting

### ISSUE THREAD

**Issue by rickychandra** [ksprojects/protobuf-jetbrains-plugin#156]
**Is your feature request related to a problem? Please describe.**
This plugin will automatically format an opened proto file, but sometimes we're working on an existing project which doesn't have (and need) formatting at all.

**Describe the solution you'd like**
An option to turn off code formatting in the Preferences.

**Additional context**
-

**Comment by kshchepanovskyi** [comment]
This plugin is not supported anymore. Please switch to https://github.com/jvolkman/intellij-protobuf-editor/
