### ISSUE TITLE
Does not work with a stand-alone proto repo

### ISSUE THREAD

**Issue by bryanhughes** [ksprojects/protobuf-jetbrains-plugin#157]
**Describe the bug**
We have our proto's in their own repo. Unfortunately your plugin does not understand this.

**To Reproduce**
1. Create a project
2. Create two subdirectories: `rpc` and `public`
4. Put grpc proto's in `rpc` and then some public messages in `public`. Include some public messages in your rpc.

**Expected behavior**
It should resolve the files, or at least give you the option to set the root.

**Screenshot**
<img width="1904" alt="Screen Shot 2021-01-31 at 5 48 17 PM" src="https://user-images.githubusercontent.com/21214/106403645-f17f1000-63ec-11eb-9f38-b70da98bc7c3.png">

**Plugin (please complete the following information):**
 - OS: MacBook Pro (16-inch, 2019) with 32GB RAM
 - Plugin version: 2.2.0
 - IDE: 
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 25, 2021
Licensed to Bryan Hughes
Subscription is active until June 28, 2021.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: idea.plugin.protoeditor, org.jetbrains.erlang, mobi.hsz.idea.gitignore

**Comment by jvolkman** [comment]
It looks like you're using https://github.com/jvolkman/intellij-protobuf-editor. You can either mark the directories as source roots or add custom paths in protobuf language settings.
