### ISSUE TITLE
Is it possible to use plain imports in protobuf files and resolving them by custom import paths?

### ISSUE THREAD

**Issue by lolgear** [ksprojects/protobuf-jetbrains-plugin#158]
**Is your feature request related to a problem? Please describe.**
I have a project with protobuf files. Of course.
Some of these files depend on others.

```
import "custom/import/file.proto"
```

My target is a binary library with protobuf files as interfaces (to generate bindings to this library).
When I build a release of library, I also include all protobuf files with its raw ( project-oriented ) paths.
I would like to change imports either at build phase or even in project.

**Describe the solution you'd like**
I would like to know if this plugin support custom imports for this case.
If I import only folders of protobuf files, could I change import statements to include only these files?
If no, it would be nice to have this option.

For example, it would be possible:
```
import "file.proto"
```

To achieve that you should add import path ( folder ).

1. Add import path. "custom/import"
2. Change proto.

Of course, this solution should support navigation via IDE. 
So, import statements in protos should be resolved to project-structured paths.

**Comment by jvolkman** [comment]
@lolgear are you sure this is the plugin you're using? It's been unsupported for a while.

**Comment by lolgear** [comment]
Not sure, I followed a link from google search results.

**Comment by kshchepanovskyi** [comment]
This plugin is not supported anymore. Please switch to https://github.com/jvolkman/intellij-protobuf-editor/
