### ISSUE TITLE
Built in option 'go_package' not found

### ISSUE THREAD

**Issue by iwind** [ksprojects/protobuf-jetbrains-plugin#162]
Thank you for hard work! I used to use Protobuf Support to highlight my .proto file, but it's not working after GoLand 2021.2, so i installed Protobuf Plugin @ HIGAN, but it's has some issues here:

Environment: 
GoLand 2021.2
Protobuf Plugin HIGAN 1.4.1

.proto file: 
~~~protobuf
syntax = "proto3";
option go_package = "./pb";

package pb;

import "models/model_admin.proto";
import "models/model_admin_list.proto";
import "models/rpc_messages.proto";
import "service_server_stat_board.proto";
~~~

Issues:
1. Built in option 'go_package' not found
2. Imported file 'xxx' not found

**Comment by iwind** [comment]
I added my protos dirs to Language & Frameworks / Protobuf, and "imported file not found" are missing.

**Comment by jvolkman** [comment]
This plugin is no longer supported. See the official plugin at
https://plugins.jetbrains.com/plugin/14004-protocol-buffers

**Comment by iwind** [comment]
Thank you! I will give a try.
