### ISSUE TITLE
reserved keyword in enum

### ISSUE THREAD

**Issue by picc09** [ksprojects/protobuf-jetbrains-plugin#96]
From version 3.5.0 protobuf supports the reserved inside the enum.
The plugin doesn't seem to support this possibility.

**Comment by kshchepanovskyi** [comment]
Correct, latest version (0.10.2) does not support it.

**Comment by geekmdtravis** [comment]
I agree, this would be an excellent feature. Presently, the state of the plugin is such that I basically have to open a different text editor when I want to work on protocol buffers. My brain can't seem to function properly with all of the red lines.

![reserved_keyword_error](https://user-images.githubusercontent.com/41837536/43371400-ed2e51b6-9345-11e8-89d5-518570a5415d.png)
